---

- name: "update local apt repo"
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt package"
  become: true
  apt:
    upgrade: yes

- name: "remove stale dependencies"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Extract Artifact"
  become: true
  unarchive:
    src: ../../artifacts.tar.gz
    dest: .
    remote_src: yes

- name: "Start app"
  become: yes
  shell: |
    pm2 delete all
    pm2 start npm -- start

